name: round_spot
description: An easy to use heatmap interface analysis library
author: Stanisław Góra <contact@sgora.dev>
repository: https://github.com/stasgora/round-spot

version: 0.1.0-dev

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^6.0.0
  path_provider: ^2.0.1
  simple_cluster: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  effective_dart: ^1.3.1
